"""运行所有测试"""
import sys
import os

# 添加项目根目录到路径
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
# 添加测试目录到路径
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

print("=" * 60)
print("Universal Controller v3.17.12 - Complete Test Suite")
print("=" * 60)

print("\n[1/9] Running Core Tests...")
print("-" * 40)
from .test_core import *
test_control_output_copy()
test_trajectory_get_velocities_unified()
test_diagnostics_v2_to_ros_msg()
test_default_config_completeness()
test_get_config_value()
test_transform_status()
test_trajectory_copy()

print("\n[2/9] Running Component Tests...")
print("-" * 40)
from .test_components import *
test_adaptive_ekf()
test_temporal_valid_requires_two_samples()
test_state_machine_counter_reset()
test_timeout_monitor()
test_safety_monitor()
test_mpc_horizon_dynamic_adjustment()
test_pure_pursuit_shutdown()
test_mpc_health_monitor()
test_consistency_analyzer()

print("\n[3/9] Running TF2 Transform Tests (F3)...")
print("-" * 40)
from .test_tf2_transform import *
test_tf2_transform_basic()
test_tf2_fallback_degradation()
test_tf2_recovery_correction()
test_tf2_transform_with_velocity()
test_tf2_status_reporting()
test_tf2_reset()

print("\n[4/9] Running Attitude Controller Tests (F14)...")
print("-" * 40)
from .test_attitude_controller import *
test_attitude_controller_basic()
test_attitude_rate_limits()
test_hover_yaw_compensation()
test_position_attitude_decoupled()
test_thrust_calculation()
test_controller_reset()

print("\n[5/9] Running Integration Tests...")
print("-" * 40)
from .test_integration import *
test_controller_manager_initialize()
test_controller_manager_update()
test_controller_manager_with_imu()
test_diagnostics_publish()
test_component_delayed_binding()
test_state_transition()
test_reset_and_shutdown()
test_tracking_error_computation()
test_mpc_degraded_horizon()

print("\n[6/9] Running EKF Estimator Tests...")
print("-" * 40)
from .test_ekf_estimator import *
test_ekf_initialization()
test_ekf_predict()
test_ekf_odom_update()
test_ekf_imu_update()
test_ekf_slip_detection()
test_ekf_anomaly_detection()
test_ekf_drift_correction()
test_ekf_covariance_positive_definite()
test_ekf_reset()
test_ekf_continuous_operation()
test_ekf_heading_fallback()

print("\n[7/9] Running Tracker Tests...")
print("-" * 40)
from .test_trackers import *
test_mpc_basic_compute()
test_mpc_velocity_constraints()
test_mpc_horizon_adjustment()
test_mpc_health_metrics()
test_mpc_fallback_solver()
test_pure_pursuit_basic()
test_pure_pursuit_lookahead()
test_pure_pursuit_omni()
test_pure_pursuit_3d()
test_pure_pursuit_heading_modes()
test_tracker_velocity_smoothing()
test_tracker_empty_trajectory()
test_tracker_performance()

print("\n[8/9] Running System Usability Tests...")
print("-" * 40)
from .test_system_usability import *
test_end_to_end_control_loop()
test_trajectory_tracking_accuracy()
test_differential_platform()
test_omni_platform()
test_quadrotor_platform()
test_ackermann_platform()
test_state_machine_full_cycle()
test_empty_trajectory_handling()
test_nan_input_handling()
test_recovery_from_mpc_failure()
test_control_loop_performance()
test_diagnostics_completeness()
test_diagnostics_callback()
test_config_validation_integration()

print("\n[9/9] Running Configuration Effects Tests...")
print("-" * 40)
from .test_config_effects import *
test_velocity_constraint_config()
test_omega_constraint_config()
test_acceleration_constraint_config()
test_odom_timeout_config()
test_startup_grace_config()
test_trajectory_grace_config()
test_ekf_slip_threshold_config()
test_ekf_measurement_noise_config()
test_ekf_heading_fallback_config()
test_mpc_horizon_config()
test_mpc_weights_config()
test_mpc_health_monitor_config()
test_consistency_alpha_min_config()
test_consistency_weights_config()
test_consistency_thresholds_config()
test_safety_velocity_margin_config()
test_safety_stop_threshold_config()
test_state_machine_recovery_config()
test_pure_pursuit_lookahead_config()
test_pure_pursuit_heading_gain_config()
test_transition_tau_config()
test_transition_max_duration_config()
test_platform_output_frame_config()
test_platform_constraints_config()
test_full_config_integration()
test_config_hot_reload()

print("\n" + "=" * 60)
print("✅ ALL TESTS PASSED - v3.17.12 Requirements Verified")
print("=" * 60)
print("\n系统可用性评估: 通过")
print("- 核心数据类型: 正常")
print("- 组件功能: 正常")
print("- TF2 变换: 正常")
print("- 姿态控制: 正常")
print("- 集成测试: 正常")
print("- EKF 估计器: 正常")
print("- 轨迹跟踪器: 正常")
print("- 系统可用性: 正常")
print("- 配置功能: 正常")
